/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
/**
 *
 * @author Miss P
 */
public class hedgeYourBetUsingFile extends javax.swing.JFrame {
    private int questionNumber = 0;
private int score = 0;

private String[] questions = {
    "Which continent is Egypt located in?",
    "Which continent is Japan located in?",
    "Which continent is France located in?",
    "Which continent is Nigeria located in?",
    "Which continent is China located in?"
};

// 0 = Africa, 1 = Asia, 2 = Europe
private int[] correctAnswers = {
    0,
    1,
    2,
    0,
    1
};

private final String FILE_NAME = "previousScore.txt";
private int readPreviousScore() {

    try {

        File file = new File(FILE_NAME);

        if (!file.exists()) {
            return 0;
        }

        BufferedReader reader =
                new BufferedReader(
                        new FileReader(file)
                );

        String scoreText = reader.readLine();

        reader.close();

        if (scoreText != null) {
            return Integer.parseInt(scoreText);
        }

    } catch (IOException | NumberFormatException e) {

        return 0;
    }

    return 0;
}
private void saveScore(int score) {

    try {

        BufferedWriter writer =
                new BufferedWriter(
                        new FileWriter(FILE_NAME)
                );

        writer.write(String.valueOf(score));

        writer.close();

    } catch (IOException e) {

        jLabel3.setText(
                "Error saving score."
        );
    }
}
 private void displayQuestion() {

    jLabel2.setText(
            "Question " + (questionNumber + 1)
            + ": " + questions[questionNumber]
    );

    jCheckBox1.setSelected(false);
    jCheckBox2.setSelected(false);
    jCheckBox3.setSelected(false);
}

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(hedgeYourBetUsingFile.class.getName());

    /**
     * Creates new form hedgeYourBetUsingFile
     */
   public hedgeYourBetUsingFile() {

    initComponents();

    int previousScore = readPreviousScore();

    jLabel1.setText(
            "Previous Score: " + previousScore
    );

    displayQuestion();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Previous Score: 0");

        jLabel2.setText("Question");

        jCheckBox1.setText("Africa");

        jCheckBox2.setText("Asia");

        jCheckBox3.setText("Europe");

        jButton1.setText("Submit Answer");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel3.setText("Feedback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButton1))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    int numberSelected = 0;

    if (jCheckBox1.isSelected()) {
        numberSelected++;
    }

    if (jCheckBox2.isSelected()) {
        numberSelected++;
    }

    if (jCheckBox3.isSelected()) {
        numberSelected++;
    }

    if (numberSelected == 0) {
        jLabel3.setText("Please select at least one answer.");
        return;
    }

    boolean correct = false;

    if (correctAnswers[questionNumber] == 0
            && jCheckBox1.isSelected()) {
        correct = true;
    }

    if (correctAnswers[questionNumber] == 1
            && jCheckBox2.isSelected()) {
        correct = true;
    }

    if (correctAnswers[questionNumber] == 2
            && jCheckBox3.isSelected()) {
        correct = true;
    }

    if (correct) {

        if (numberSelected == 1) {
            score += 5;
        } else if (numberSelected == 2) {
            score += 2;
        } else if (numberSelected == 3) {
            score += 1;
        }

        jLabel3.setText("Correct! Score: " + score);

    } else {

        jLabel3.setText("Incorrect! Score: " + score);
    }

    questionNumber++;

    if (questionNumber == questions.length) {

        String message;

        if (score > 21) {
            message = "Fantastic!";
        } else if (score > 15) {
            message = "Very good";
        } else {
            message = "OK";
        }

        saveScore(score);

        jLabel2.setText(
                "Quiz Complete! Final Score: " + score + "/25"
        );

        jLabel3.setText(message);

        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jButton1.setEnabled(false);

    } else {

    displayQuestion();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new hedgeYourBetUsingFile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
